/**
 * Recipe Bank — cookbook cards for Health Map.
 * @typedef {{
 *   title: string,
 *   image: string,
 *   serves: number,
 *   minutes: number,
 *   calories: number,
 *   protein: number,
 *   carbs: number,
 *   fat: number,
 *   ingredients: string[],
 *   steps: string[],
 *   tip?: string
 * }} Recipe
 */

const img = (id) => `https://images.unsplash.com/${id}?w=960&q=80`;

/** @type {Record<string, Recipe>} */
export const RECIPES = {
  "paneer-moong-dosa": {
    title: "Paneer-Moong Dal Stuffed Dosa",
    image: img("photo-1589301760014-d929f3979dbc"),
    serves: 1,
    minutes: 20,
    calories: 480,
    protein: 23,
    carbs: 60,
    fat: 16,
    ingredients: [
      "Fresh dosa batter — 180g",
      "Paneer, crumbled — 60g",
      "Cooked yellow moong dal — 4 tbsp",
      "Cumin seeds — ¼ tsp",
      "Turmeric — ¼ tsp",
      "Oil — 1.5 tsp",
      "Coconut chutney (no mint) — 2 tbsp",
    ],
    steps: [
      "Mix paneer, moong dal, cumin, turmeric, and a pinch of salt for the stuffing.",
      "Heat a non-stick tawa, grease lightly with ¼ tsp oil.",
      "Pour a ladle of batter, spread thin in a circular motion.",
      "Once edges lift, place stuffing in the center, fold.",
      "Cook 1–2 min till golden. Repeat for a second dosa.",
      "Serve hot with coconut chutney.",
    ],
    tip: "Skip tamarind chutney (acidity trigger). Coconut only. Instant rice-suji dosa mix works if batter is short.",
  },
  "veg-paneer-daliya": {
    title: "Vegetable-Paneer Daliya",
    image: img("photo-1505253758473-96b7015fcd40"),
    serves: 1,
    minutes: 15,
    calories: 470,
    protein: 20,
    carbs: 52,
    fat: 17,
    ingredients: [
      "Broken wheat (daliya) — 50g",
      "Paneer, cubed — 50g",
      "Mixed vegetables (peas, carrot) — 50g",
      "Ghee — 1 tsp",
      "Cumin seeds — ¼ tsp",
      "Milk — 50ml",
      "Curd, side — 100g",
    ],
    steps: [
      "Dry roast daliya 2 min till aromatic, set aside.",
      "Heat ghee, splutter cumin, add vegetables, sauté 2 min.",
      "Add daliya, 1.5 cups water, salt. Simmer 10 min till soft.",
      "Stir in paneer cubes and milk in the last 2 min.",
      "Serve warm with curd on the side.",
    ],
    tip: "Cooks well in bulk. Splash of milk when reheating leftovers.",
  },
  "ragi-idli": {
    title: "Ragi/Oats Idli with Peanut Podi",
    image: img("photo-1741376509109-e9edd6f24f5f"),
    serves: 1,
    minutes: 15,
    calories: 455,
    protein: 16,
    carbs: 56,
    fat: 19,
    ingredients: [
      "Ragi or oats idli batter — 200g (4 idlis)",
      "Coconut chutney (no mint) — 2 tbsp",
      "Curd — 100g",
      "Roasted peanut podi — 2 tbsp",
    ],
    steps: [
      "Steam idli batter in a greased idli mould, 10–12 min till a knife comes out clean.",
      "Serve 4 idlis with chutney, curd, and peanut podi on the side.",
    ],
    tip: "Batch peanut podi once a week — keeps for days.",
  },
  "masala-omelette": {
    title: "Masala Vegetable Omelette + Toast",
    image: img("photo-1572449043416-55f4685c9bb7"),
    serves: 1,
    minutes: 12,
    calories: 405,
    protein: 24,
    carbs: 30,
    fat: 22,
    ingredients: [
      "Eggs — 3 whole",
      "Capsicum, finely chopped — 30g",
      "Carrot, grated — 10g",
      "Cumin powder, turmeric — pinch each",
      "Oil — 1 tsp",
      "Whole wheat bread — 2 slices, toasted",
    ],
    steps: [
      "Whisk eggs with a pinch of salt, cumin, and turmeric.",
      "Heat oil in a non-stick pan, add capsicum and carrot, sauté 1–2 min.",
      "Pour whisked eggs over the vegetables, let set on medium-low heat.",
      "Fold in half once mostly set, cook 1 more min.",
      "Serve with toasted bread.",
    ],
    tip: "Keep onion out or minimal if it's a personal trigger.",
  },
  "boiled-eggs": {
    title: "Boiled Eggs",
    image: img("photo-1680987398307-e1ae27a6ed67"),
    serves: 1,
    minutes: 12,
    calories: 210,
    protein: 18,
    carbs: 1.5,
    fat: 15,
    ingredients: [
      "Eggs — 3 whole",
      "Salt, pepper (mild) — pinch",
      "Water — enough to submerge eggs",
    ],
    steps: [
      "Place eggs in a saucepan, cover with water by 1 inch.",
      "Bring to a boil, reduce heat, simmer 8–10 min for firm yolks (7 min for slightly soft).",
      "Transfer to cold water immediately, sit 2 min, then peel.",
      "Season with salt and pepper.",
    ],
    tip: "Boil 6–9 at once. Keep 4–5 days refrigerated, unpeeled.",
  },
  "buttermilk-makhana": {
    title: "Buttermilk + Roasted Makhana",
    image: img("photo-1546069901-ba9599a7e63c"),
    serves: 1,
    minutes: 5,
    calories: 245,
    protein: 9,
    carbs: 27,
    fat: 9,
    ingredients: [
      "Buttermilk (chaas) — 250ml",
      "Makhana (fox nuts) — 30g",
      "Ghee — ½ tsp",
      "Roasted cumin powder, salt — pinch",
      "Almonds — 8–10 pieces",
    ],
    steps: [
      "Dry roast makhana in ½ tsp ghee till crisp, 4–5 min.",
      "Whisk buttermilk with roasted cumin and salt (no mint).",
      "Serve together with a small handful of almonds.",
    ],
  },
  "sprouts-chaat": {
    title: "Sprouts Chaat",
    image: img("photo-1615485290382-441e4d049cb5"),
    serves: 1,
    minutes: 5,
    calories: 215,
    protein: 13,
    carbs: 25,
    fat: 8,
    ingredients: [
      "Mixed sprouts (moong + chana), boiled — 100g",
      "Cucumber, chopped — 50g",
      "Roasted peanuts — 15g",
      "Chaat masala, salt — pinch (skip if it contains amchur/citrus)",
    ],
    steps: [
      "Boil sprouts 5 min till just tender, drain.",
      "Toss with chopped cucumber, peanuts, and mild seasoning.",
    ],
    tip: "Sprout moong/chana at home over 2 days — cheaper than store-bought.",
  },
  "nuts-fruit": {
    title: "Nuts + Fruit",
    image: img("photo-1490645935967-10de6ba17061"),
    serves: 1,
    minutes: 2,
    calories: 190,
    protein: 4,
    carbs: 27,
    fat: 8,
    ingredients: [
      "Almonds or walnuts — 15g",
      "Banana, apple, or pear (non-citrus) — 1 medium",
    ],
    steps: ["Portable, zero-cook."],
  },
  "roasted-chana-banana": {
    title: "Roasted Chana + Banana",
    image: img("photo-1567620905732-2d1ec7ab7445"),
    serves: 1,
    minutes: 2,
    calories: 205,
    protein: 7,
    carbs: 43,
    fat: 2,
    ingredients: [
      "Roasted chana (chickpeas) — 30g",
      "Banana — 1 medium",
    ],
    steps: ["Grab-and-go — no cooking."],
  },
  "moong-dal-rice-lauki": {
    title: "Moong Dal, Rice & Lauki Sabzi",
    image: img("photo-1596797038530-2c107229654b"),
    serves: 1,
    minutes: 25,
    calories: 580,
    protein: 28,
    carbs: 75,
    fat: 19,
    ingredients: [
      "Yellow moong dal, cooked — 1 cup",
      "Steamed rice — ¾ cup",
      "Lauki (bottle gourd), diced — 100g",
      "Paneer, cubed — 40g",
      "Cumin, turmeric, hing — pinch each",
      "Oil — 1.5 tsp",
      "Curd, side — 100g",
      "Cucumber salad — small bowl",
    ],
    steps: [
      "Cook moong dal with turmeric and hing till soft; temper with cumin in ½ tsp oil.",
      "Sauté lauki in 1 tsp oil till tender, season lightly, no tomato.",
      "Lightly pan-sear paneer cubes, add to the sabzi.",
      "Plate rice, dal, sabzi, curd, and cucumber salad (roasted cumin instead of lemon).",
    ],
  },
  "rajma-rice-bhindi": {
    title: "Rajma, Rice & Bhindi Sabzi",
    image: img("photo-1565557623262-b51c2513a641"),
    serves: 1,
    minutes: 25,
    calories: 505,
    protein: 21,
    carbs: 82,
    fat: 10,
    ingredients: [
      "Rajma (kidney beans), cooked — 1 cup",
      "Steamed rice — ¾ cup",
      "Bhindi (okra), sliced — 100g",
      "Cumin, ginger, mild spices — pinch",
      "Oil — 1.5 tsp",
      "Curd, side — 100g",
    ],
    steps: [
      "Simmer cooked rajma with cumin, ginger, and a touch of turmeric — minimal to no tomato.",
      "Sauté bhindi in 1 tsp oil on medium heat till just cooked.",
      "Serve with rice and curd.",
    ],
    tip: "Pressure cook rajma on Sunday, portion and freeze — 15 min meal on the day.",
  },
  "chole-roti": {
    title: "Chole, Roti & Salad",
    image: img("photo-1601050690597-df0568f70950"),
    serves: 1,
    minutes: 20,
    calories: 445,
    protein: 22,
    carbs: 72,
    fat: 8,
    ingredients: [
      "Chole (chickpeas), cooked — 1 cup",
      "Whole wheat roti — 2 medium",
      "Cumin, coriander powder, mild spice — pinch",
      "Oil — 1 tsp",
      "Curd, side — 100g",
      "Cucumber-carrot salad — small bowl",
    ],
    steps: [
      "Simmer chole with cumin, coriander powder, and a touch of oil — light on tomato, no citrus finish.",
      "Serve with roti, curd, and salad.",
    ],
  },
  "paneer-bhurji": {
    title: "Paneer Bhurji + Roti",
    image: img("photo-1585937421612-70a008356fbe"),
    serves: 1,
    minutes: 15,
    calories: 440,
    protein: 25,
    carbs: 37,
    fat: 22,
    ingredients: [
      "Paneer, crumbled — 100g",
      "Capsicum, peas — 40g",
      "Cumin, turmeric, mild chili — pinch",
      "Oil — 1.5 tsp",
      "Whole wheat roti — 2 medium",
    ],
    steps: [
      "Heat oil, sauté capsicum and peas 2 min.",
      "Add crumbled paneer, cumin, turmeric — cook 3–4 min. Minimal to no tomato.",
      "Serve hot with roti and a simple salad.",
    ],
  },
  "moong-khichdi": {
    title: "Moong Dal Khichdi + Curd",
    image: img("photo-1512058564366-18510be2db19"),
    serves: 1,
    minutes: 20,
    calories: 410,
    protein: 17.5,
    carbs: 61,
    fat: 10.5,
    ingredients: [
      "Rice — ½ cup",
      "Split moong dal — ½ cup",
      "Cumin, turmeric, hing — pinch each",
      "Ghee — 1 tsp",
      "Curd, side — 150g",
    ],
    steps: [
      "Wash rice and dal together, pressure cook with turmeric, hing, and 2 cups water — 3 whistles.",
      "Temper with cumin in ghee, stir through.",
      "Serve warm with curd.",
    ],
  },
  "tofu-paneer-stirfry": {
    title: "Tofu-Paneer Stir-Fry + Rice",
    image: img("photo-1617093727343-374698b1b08d"),
    serves: 1,
    minutes: 15,
    calories: 425,
    protein: 21,
    carbs: 38,
    fat: 20,
    ingredients: [
      "Tofu, cubed — 100g",
      "Paneer, cubed — 50g",
      "Mixed vegetables (beans, carrot, capsicum) — 80g",
      "Oil — 1.5 tsp",
      "Cumin, mild pepper — pinch",
      "Steamed rice — ¾ cup",
    ],
    steps: [
      "Pan-sear tofu and paneer cubes in 1 tsp oil till lightly golden.",
      "Add vegetables, stir-fry 4–5 min on medium-high.",
      "Season lightly, serve over rice.",
    ],
  },
  "palak-paneer": {
    title: "Palak Paneer + Roti",
    image: img("photo-1576045057995-568f588f82fb"),
    serves: 1,
    minutes: 20,
    calories: 435,
    protein: 22,
    carbs: 45,
    fat: 20,
    ingredients: [
      "Spinach (palak), blanched & pureed — 150g",
      "Paneer, cubed — 80g",
      "Cumin, ginger — pinch",
      "Oil — 1.5 tsp",
      "Whole wheat roti — 2 medium",
    ],
    steps: [
      "Blanch spinach 2 min, blend to a smooth puree.",
      "Heat oil, temper cumin and ginger, add spinach puree, simmer 5 min.",
      "Add paneer cubes, simmer 2–3 min more. No cream, minimal salt.",
      "Serve with roti.",
    ],
  },
  "egg-curry": {
    title: "Egg Curry + Rice",
    image: img("photo-1547592166-23ac45744acd"),
    serves: 1,
    minutes: 20,
    calories: 455,
    protein: 23,
    carbs: 38,
    fat: 23,
    ingredients: [
      "Eggs — 3, boiled and peeled",
      "Curd — 50g",
      "Onion, finely chopped (optional) — 20g",
      "Cumin, turmeric, mild chili powder — pinch each",
      "Oil — 1.5 tsp",
      "Steamed rice — ¾ cup",
    ],
    steps: [
      "Heat oil, sauté onion (if using) till soft, 2–3 min.",
      "Add cumin, turmeric, chili powder, cook 30 sec.",
      "Whisk in curd off-heat to avoid curdling, return to low heat, simmer 3–4 min into a light gravy.",
      "Halve the boiled eggs, add to the gravy, simmer 2 min to warm through.",
      "Serve over rice.",
    ],
    tip: "Curd-based gravy instead of tomato — gentler on acidity.",
  },
};

/**
 * @param {string} id
 * @returns {(Recipe & { id: string }) | null}
 */
export function getRecipe(id) {
  const recipe = RECIPES[id];
  return recipe ? { id, ...recipe } : null;
}

/**
 * @param {string[]} ids
 * @returns {Array<Recipe & { id: string }>}
 */
export function getRecipes(ids) {
  return ids.map((id) => getRecipe(id)).filter(Boolean);
}
